id: dk-ehmi-sbdh
canonical: http://medcomehmi.dk/ig/dk-ehmi-sbdh
name: DK EHMI SBDH IG
title: "DK EHMI SBDH IG"
description: The DK EHMI SBDH IG
status: active # draft | active | retired | unknown
version: 2.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://medcom.dk
  # email: test@example.org


dependencies:
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 4.0.1
  medcom.fhir.dk.terminology: 2.0.2
  dk.ehmi.terminology: current #1.0.0
  dk.ehmi.eer:  current #1.0.0
  medcom.fhir.dk.xdsmetadata: current #2.0.0
  medcom.fhir.dk.document: 2.0.0

menu:
  Home: index.html
  ehmiSBDH: 
    ehmiSBDH: ehmiSBDH.html
    ehmiSBDH Reliable Messaging: ehmiSBDHReliableMessaging.html
  ehmiSbdhschemas: 
    StandardBusinessDocumentHeader: ehmiSBDH_StandardBusinessDocumentHeader.xsd.html
    Partner: ehmiSBDH_Partner.xsd.html
    DocumentIdentification: ehmiSBDH_DocumentIdentification.xsd.html
    BusinessScope: ehmiSBDH_BusinessScope.xsd.html
    BinaryContentType: ehmiSBDH_EDN-Business-Message-Envelope-1.2.xsd.html
    BasicTypes: ehmiSBDH_BasicTypes.xsd.html
    Manifest: ehmiSBDH_Manifest.xsd.html
    ebbp-signals-2.0.4: ehmiSBDH_ebbp-signals-2.0.4.xsd.html
  sample xmls:
    ehmiMessage_sample.xml: ehmiMessage_fullsample.xml.html
    ehmiMessage_ack_sample.xml: ehmiMessage_fullsample_Ack.xml.html
    ehmisbdh_sample.xml: ehmisbdh_fullsample.xml.html
#    ehmisbdh_ack_sample.xml: ehmisbdh_fullsample_ack.xml.html
    ehmisbdh_fullsample_sbdhAck.xml: ehmisbdh_fullsample_sbdhAck.xml.html
    ehmiMessage_401cbc36-db1e-4fe0-bf90-6df331dde179_HCO: sample_ehmiMessage_401cbc36-db1e-4fe0-bf90-6df331dde179_HCO.xml.html
    ehmiSBDH_9a6ff822-08de-5a6f-9670-9fa4b9d2f0dc_HCO_full: sample_ehmiSBDH_9a6ff822-08de-5a6f-9670-9fa4b9d2f0dc_HCO_full.xml.html
  SBDH original schemas: 
    StandardBusinessDocumentHeader: SBDH_StandardBusinessDocumentHeader.xsd.html
    Partner: SBDH_Partner.xsd.html
    DocumentIdentification: SBDH_DocumentIdentification.xsd.html
    BusinessScope: SBDH_BusinessScope.xsd.html
  Artifacts: artifacts.html
  Test examples:
    ehmiMessage HCO (json): TestExample_ehmiMessage_HCO.json.html
    ehmiSBDH HCO Embedded (xml): TestExampleEmbeddedHCO.xml.html # filename should be changed in the future to the following line
    # ehmiSBDH HCO Embedded (xml): TestExample_ehmiSBDH_Embedded_HCO.xml.html
    ehmiSBDH HCO Embedded for DDS (json): TestExampleXDSEmbeddedHCO.xml.html # filename should be changed in the future to the following line
    # ehmiSBDH HCO Embedded for DDS (json): TestExample_ehmiSBDH_Embedded_HCO_for_DDS.xml.html
    ehmiMessage FHIR Acknowledgement (json): TestExampleEmbeddedFHIRAckSBDH.xml.html # filename should be changed in the future to the following line
    ehmiSBDH FHIR Acknowledgement Embedded (xml): TestExampleEmbeddedFHIRAckSBDH.xml.html # filename should be changed in the future to the following line
    # ehmiSBDH FHIR Acknowledgement Embedded (xml): TestExample_ehmiSBDH_Embedded_FHIR_Ack.xml.html
    ehmiMessage ehmiSBDH-Acknowledgement (xml): TestExample_ehmiMessage_SBDHAck.xml_raw.html
    ehmiSBDH ehmiSBDH-Acknowledgement Embedded (xml): TextExampleSBDHAck.xml.html # filename should be changed in the future to the following line
    # ehmiSBDH SBDHAck: TestExample_ehmiSBDH_Embedded_SBDHAck.xml.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html
instanceOptions:
  manualSliceOrdering: true # true | false
